branch-defaults:
  default:
    environment: dinorunio-dev
    group_suffix: null
  master:
    environment: dinorunio-dev
global:
  application_name: dinorunio
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
